#鈴耶
「代わり身の術！！」[p]
[eval exp="f.dress=2 , f.invincible=0"]
[call storage="asset/As_face.ks"]
[if exp="f.ERO > 700"]
[chara_mod name="suzune" face="喘ぎ" ]
[else]
[chara_mod name="suzune" face="厳しい" ]
[endif]
[return]
